#ifndef CONFIG_H
#define CONFIG_H

#include <stdint.h>

#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_DISPLAY_WIDTH 64
#define CHIP8_DISPLAY_HEIGHT 32
#define WINDOW_SIZE_MULTIPLIER 10
#define EMULATOR_WINDOW_TITLE "CHIP-8"
#define CHIP8_NUMBER_OF_DATA_REGISTERS 16
#define CHIP8_PROGRAM_LOAD_ADDRESSE 0x200
#define CHIP8_STACK_DEPTH 16
#define CHIP8_TOTAL_KEYS 16
#define CHIP8_SPRITE_MAX_SIZE 15


#endif